use prost::Message;

use hdfs_types::common::*;
use hdfs_types::hdfs::*;

use crate::IpcConnection;
use crate::IpcError;

use super::method;

method! { IpcConnection<S> =>
    create, "create", CreateRequestProto, CreateResponseProto;
    get_server_defaults, "getServerDefaults", GetServerDefaultsRequestProto,GetServerDefaultsResponseProto;
    get_block_locations, "getBlockLocations", GetBlockLocationsRequestProto, GetBlockLocationsResponseProto;
    append, "append", AppendRequestProto, AppendResponseProto;
    set_replication, "setReplication", SetReplicationRequestProto, SetReplicationResponseProto;
    set_storage_policy, "setStoragePolicy", SetStoragePolicyRequestProto, SetStoragePolicyResponseProto;
    unset_storage_policy, "unsetStoragePolicy", UnsetStoragePolicyRequestProto, UnsetStoragePolicyResponseProto;
    get_storage_policy, "getStoragePolicy", GetStoragePolicyRequestProto, GetStoragePolicyResponseProto;
    get_storage_policies, "getStoragePolicies", GetStoragePoliciesRequestProto, GetStoragePoliciesResponseProto;
    set_permission, "setPermission", SetPermissionRequestProto, SetPermissionResponseProto;
    set_owner, "setOwner", SetOwnerRequestProto, SetOwnerResponseProto;
    abandon_block, "abandonBlock", AbandonBlockRequestProto, AbandonBlockResponseProto;
    add_block, "addBlock", AddBlockRequestProto, AddBlockResponseProto;
    get_additional_datanode, "getAdditionalDatanode", GetAdditionalDatanodeRequestProto, GetAdditionalDatanodeResponseProto;
    complete, "complete", CompleteRequestProto, CompleteResponseProto;
    report_bad_blocks, "reportBadBlocks", ReportBadBlocksRequestProto, ReportBadBlocksResponseProto;
    concat, "concat", ConcatRequestProto, ConcatResponseProto;
    truncate, "truncate", TruncateRequestProto, TruncateResponseProto;
    rename, "rename", RenameRequestProto, RenameResponseProto;
    rename2, "rename2", Rename2RequestProto, Rename2ResponseProto;
    delete, "delete", DeleteRequestProto, DeleteResponseProto;
    mkdirs, "mkdirs", MkdirsRequestProto, MkdirsResponseProto;
    get_listing, "getListing", GetListingRequestProto, GetListingResponseProto;
    renew_lease, "renewLease", RenewLeaseRequestProto, RenewLeaseResponseProto;
    recover_lease, "recoverLease", RecoverLeaseRequestProto, RecoverLeaseResponseProto;
    get_fs_stats, "getFsStats", GetFsStatusRequestProto, GetFsStatsResponseProto;
    get_datanode_report, "getDatanodeReport", GetDatanodeReportRequestProto, GetDatanodeReportResponseProto;
    get_preferred_block_size, "getPreferredBlockSize", GetPreferredBlockSizeRequestProto, GetPreferredBlockSizeResponseProto;
    set_safe_mode, "setSafeMode", SetSafeModeRequestProto, SetSafeModeResponseProto;
    save_namespace, "saveNamespace", SaveNamespaceRequestProto, SaveNamespaceResponseProto;
    roll_edits, "rollEdits", RollEditsRequestProto, RollEditsResponseProto;
    restore_failed_storage, "restoreFailedStorage", RestoreFailedStorageRequestProto, RestoreFailedStorageResponseProto;
    refresh_nodes, "refreshNodes", RefreshNodesRequestProto, RefreshNodesResponseProto;
    finalize_upgrade, "finalizeUpgrade", FinalizeUpgradeRequestProto, FinalizeUpgradeResponseProto;
    upgrade_status, "upgradeStatus", UpgradeStatusRequestProto, UpgradeStatusResponseProto;
    rolling_upgrade, "rollingUpgrade", RollingUpgradeRequestProto, RollingUpgradeResponseProto;
    list_corrupt_file_blocks, "listCorruptFileBlocks", ListCorruptFileBlocksRequestProto, ListCorruptFileBlocksResponseProto;
    meta_save, "metaSave", MetaSaveRequestProto, MetaSaveResponseProto;
    get_file_info, "getFileInfo", GetFileInfoRequestProto, GetFileInfoResponseProto;
    get_located_file_info, "getLocatedFileInfo", GetLocatedFileInfoRequestProto, GetLocatedFileInfoResponseProto;
    add_cache_pool, "addCachePool", AddCachePoolRequestProto, AddCachePoolResponseProto;
    modify_cache_pool, "modifyCachePool", ModifyCachePoolRequestProto, ModifyCachePoolResponseProto;
    remove_cache_pool, "removeCachePool", RemoveCachePoolRequestProto, RemoveCachePoolResponseProto;
    list_cache_pools, "listCachePools", ListCachePoolsRequestProto, ListCachePoolsResponseProto;
    get_file_link_info, "getFileLinkInfo", GetFileLinkInfoRequestProto, GetFileLinkInfoResponseProto;
    get_content_summary, "getContentSummary", GetContentSummaryRequestProto, GetContentSummaryResponseProto;
    set_quota, "setQuota", SetQuotaRequestProto, SetQuotaResponseProto;
    fsync, "fsync", FsyncRequestProto, FsyncResponseProto;
    set_times, "setTimes", SetTimesRequestProto, SetTimesResponseProto;
    create_symlink, "createSymlink", CreateSymlinkRequestProto, CreateSymlinkResponseProto;
    get_link_target, "getLinkTarget", GetLinkTargetRequestProto, GetLinkTargetResponseProto;
    update_block_for_pipeline, "updateBlockForPipeline", UpdateBlockForPipelineRequestProto, UpdateBlockForPipelineResponseProto;
    update_pipeline, "updatePipeline", UpdatePipelineRequestProto, UpdatePipelineResponseProto;
    set_balancer_bandwidth, "setBalancerBandwidth", SetBalancerBandwidthRequestProto, SetBalancerBandwidthResponseProto;
    get_data_encryption_key, "getDataEncryptionKey", GetDataEncryptionKeyRequestProto, GetDataEncryptionKeyResponseProto;
    create_snapshot, "createSnapshot", CreateSnapshotRequestProto, CreateSnapshotResponseProto;
    rename_snapshot, "renameSnapshot", RenameSnapshotRequestProto, RenameSnapshotResponseProto;
    allow_snapshot, "allowSnapshot", AllowSnapshotRequestProto, AllowSnapshotResponseProto;
    disallow_snapshot, "disallowSnapshot", DisallowSnapshotRequestProto, DisallowSnapshotResponseProto;
    get_snapshot_listing, "getSnapshotListing", GetSnapshotListingRequestProto, GetSnapshotListingResponseProto;
    delete_snapshot, "deleteSnapshot", DeleteSnapshotRequestProto, DeleteSnapshotResponseProto;
    get_snapshot_diff_report, "getSnapshotDiffReport", GetSnapshotDiffReportRequestProto, GetSnapshotDiffReportResponseProto;
    is_file_closed, "isFileClosed", IsFileClosedRequestProto, IsFileClosedResponseProto;
    modify_acl_entries, "modifyAclEntries", ModifyAclEntriesRequestProto, ModifyAclEntriesResponseProto;
    remove_acl_entries, "removeAclEntries", RemoveAclEntriesRequestProto, RemoveAclEntriesResponseProto;
    remove_default_acl, "removeDefaultAcl", RemoveDefaultAclRequestProto, RemoveDefaultAclResponseProto;
    remove_acl, "removeAcl", RemoveAclRequestProto, RemoveAclResponseProto;
    set_acl, "setAcl", SetAclRequestProto, SetAclResponseProto;
    get_acl_status, "getAclStatus", GetAclStatusRequestProto, GetAclStatusResponseProto;
    set_x_attr, "setXAttr", SetXAttrRequestProto, SetXAttrResponseProto;
    get_x_attrs, "getXAttrs", GetXAttrsRequestProto, GetXAttrsResponseProto;
    list_x_attrs, "listXAttrs", ListXAttrsRequestProto, ListXAttrsResponseProto;
    remove_x_attr, "removeXAttr", RemoveXAttrRequestProto, RemoveXAttrResponseProto;
    check_access, "checkAccess", CheckAccessRequestProto, CheckAccessResponseProto;
    create_encryption_zone, "createEncryptionZone", CreateEncryptionZoneRequestProto, CreateEncryptionZoneResponseProto;
    list_encryption_zones, "listEncryptionZones", ListEncryptionZonesRequestProto, ListEncryptionZonesResponseProto;
    reencrypt_encryption_zone, "reencryptEncryptionZone", ReencryptEncryptionZoneRequestProto, ReencryptEncryptionZoneResponseProto;
    list_reencryption_status, "listReencryptionStatus", ListReencryptionStatusRequestProto, ListReencryptionStatusResponseProto;
    get_e_z_for_path, "getEZForPath", GetEzForPathRequestProto, GetEzForPathResponseProto;
    set_erasure_coding_policy, "setErasureCodingPolicy", SetErasureCodingPolicyRequestProto, SetErasureCodingPolicyResponseProto;
    get_current_edit_log_txid, "getCurrentEditLogTxid", GetCurrentEditLogTxidRequestProto, GetCurrentEditLogTxidResponseProto;
    get_edits_from_txid, "getEditsFromTxid", GetEditsFromTxidRequestProto, GetEditsFromTxidResponseProto;
    get_erasure_coding_policy, "getErasureCodingPolicy", GetErasureCodingPolicyRequestProto, GetErasureCodingPolicyResponseProto;
    get_erasure_coding_codecs, "getErasureCodingCodecs", GetErasureCodingCodecsRequestProto, GetErasureCodingCodecsResponseProto;
    get_quota_usage, "getQuotaUsage", GetQuotaUsageRequestProto, GetQuotaUsageResponseProto;
    list_open_files, "listOpenFiles", ListOpenFilesRequestProto, ListOpenFilesResponseProto;
    msync, "msync", MsyncRequestProto, MsyncResponseProto;
    satisfy_storage_policy, "satisfyStoragePolicy", SatisfyStoragePolicyRequestProto, SatisfyStoragePolicyResponseProto;
    get_ha_service_state, "getHAServiceState", HaServiceStateRequestProto, HaServiceStateResponseProto;
    get_datanode_storage_report, "getDatanodeStorageReport", GetDatanodeStorageReportRequestProto, GetDatanodeStorageReportResponseProto;
    get_snapshottable_dir_listing, "getSnapshottableDirListing", GetSnapshottableDirListingRequestProto, GetSnapshottableDirListingResponseProto;
    get_snapshot_diff_report_listing, "getSnapshotDiffReportListing", GetSnapshotDiffReportListingRequestProto, GetSnapshotDiffReportListingResponseProto;
    unset_erasure_coding_policy, "unsetErasureCodingPolicy", UnsetErasureCodingPolicyRequestProto, UnsetErasureCodingPolicyResponseProto;
    get_e_c_topology_result_for_policies, "getECTopologyResultForPolicies", GetEcTopologyResultForPoliciesRequestProto, GetEcTopologyResultForPoliciesResponseProto;
    get_erasure_coding_policies, "getErasureCodingPolicies", GetErasureCodingPoliciesRequestProto, GetErasureCodingPoliciesResponseProto;
    add_erasure_coding_policies, "addErasureCodingPolicies", AddErasureCodingPoliciesRequestProto, AddErasureCodingPoliciesResponseProto;
    remove_erasure_coding_policy, "removeErasureCodingPolicy", RemoveErasureCodingPolicyRequestProto, RemoveErasureCodingPolicyResponseProto;
    enable_erasure_coding_policy, "enableErasureCodingPolicy", EnableErasureCodingPolicyRequestProto, EnableErasureCodingPolicyResponseProto;
    disable_erasure_coding_policy, "disableErasureCodingPolicy", DisableErasureCodingPolicyRequestProto, DisableErasureCodingPolicyResponseProto;
    get_slow_datanode_report, "getSlowDatanodeReport", GetSlowDatanodeReportRequestProto, GetSlowDatanodeReportResponseProto;
}
